spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/predictorama}
spring.datasource.username=${DB_USERNAME:predictorama}
spring.datasource.password=${DB_PASSWORD:predictorama}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

football-data.base-url=https://api.football-data.org/v4
football-data.api-key=1a1b7a45f33742d9ab83624415ef38fe