spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/predictorama}
spring.datasource.username=${DB_USERNAME:predictorama}
spring.datasource.password=${DB_PASSWORD:predictorama}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

jwt.secret=${JWT_SECRET:QpqkhHrfekOKtB52hy1S/6iziGEPy23raL8M8V3b4XCSu9rMrXNJWPlRmvCI+R1DDfyRJML21aIR4k6DQy8e6Q==}
google.client-id=797345751218-omhsvur26gss54o0pcip0k51k4vcivmk.apps.googleusercontent.com