spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/predictorama}
spring.datasource.username=${DB_USERNAME:predictorama}
spring.datasource.password=${DB_PASSWORD:predictorama}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
