spring.application.name=backend
server.port=8080
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

football-data.base-url=https://api.football-data.org/v4
football-data.api-key=${FOOTBALL_DATA_API_KEY:}